name: Terraform State Backend
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  BUCKET_NAME: github-actions-terraform-state-bucket-2024
  DYNAMODB_TABLE_NAME: terraform-state-file-table-2024

jobs:
  aws-backend-terraform-state:
    runs-on: ubuntu-latest
    steps:
      - name: AuthN Against AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::224732705809:role/github-actions-terraform
          aws-region: ${{ env.AWS_REGION }}
      - name: Create S3 Bucket
        run: |
          aws s3api create-bucket \
          --bucket ${{ env.BUCKET_NAME }} \
          --region ${{ env.AWS_REGION }} \
      - name: Enable S3 Bucket Versioning
        run: |
          aws s3api put-bucket-versioning \
          --bucket ${{ env.BUCKET_NAME }} \
          --versioning-configuration Status=Enabled
      - name: Create DynamoDB Table
        run: |
          aws dynamodb create-table \
          --table-name ${{ env.DYNAMODB_TABLE_NAME }} \
          --attribute-definitions AttributeName=LockID,AttributeType=S \
          --key-schema AttributeName=LockID,KeyType=HASH \
          --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1 \
          --region ${{ env.AWS_REGION }}
