name: AWS Terraform Workflow
on:
  workflow_dispatch:
  push:

permissions:
  id-token: write

jobs:
  aws-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run Terraform Config File
        run: |
          terraform init
          terraform plan
